# Generated by Django 3.0.7 on 2020-07-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productpurchase_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='order_id',
            field=models.CharField(default='abc', max_length=120),
        ),
    ]
